Fix issues with point rounding and storage, add support for various other peripherials
openhaptics/openhaptics-firmware pull request #2
Opened 2022-09-03 01:31 UTC by sanjay900

Previously, Point2Ds were stored as pointers in a lot of collections, and this was causing issues as the pointer was staying the same and so things like the `pts` map were only ever storing one point. I changed this over to just storing Point2Ds as values, and then i was able to see all the points in the `pts` map.

Also, when constructing the outputs, i noticed that slightly different math was being used to construct outputs compared to the math used to construct the mapping to bhaptics. This caused issues with rounding, so i have changed the bhaptics logic to use the same math.

After that, i did some digging and figured out how to make it show up as a bunch of other accessories, such as  the x40, Tactal, TactGlove and Tactosy for arms / hands / feet.

I also added support for direct pwm instead of just the PCA9685, as for the other accessories you really don't want to need a PCA9685 board.

2022-09-03 02:48 UTC, sanjay900 commented
![image](https://user-images.githubusercontent.com/1862720/188252970-6989855b-badd-450e-91a1-8390a647c8e0.png)
![image](https://user-images.githubusercontent.com/1862720/188252975-86f1e88e-c2f6-425b-a368-1da7b840f5b1.png)
![image](https://user-images.githubusercontent.com/1862720/188252977-90746cf6-08a5-452c-ae53-b23e2372bfc6.png)
![image](https://user-images.githubusercontent.com/1862720/188252980-3299cada-665e-4f27-8f80-c2bd97d230c3.png)![image](https://user-images.githubusercontent.com/1862720/188252986-42be2cd7-11f3-44f1-add9-7e5878353eef.png)
![image](https://user-images.githubusercontent.com/1862720/188252988-16c2b751-5679-4cba-a6ac-23d06b6ca0e8.png)

2022-09-03 14:19 UTC, leon0399 commented
Wow! I haven't though of this project for a while, and definitely not thought somebody will show interest for it! Thank you very much for your contribution! I'll check it as soon as I get home, presumably tomorrow!
Thank you one more time!

2022-09-03 17:53 UTC, sanjay900 commented
No problem mate, I've just done a aliexpress shop so i can actually build all of these lol, will be fun when that all arrives

2022-09-04 22:04 UTC, leon0399 requested changes

2022-09-04 22:06 UTC, leon0399 commented
I'm really surprised, how you managed to figure out how my code works  without any documentation and comments! Really great work there!

2022-09-04 23:16 UTC, sanjay900 commented on firmware/output_writers/pca9685.cpp
> +        printf("%d %d\n", this->num, intensity);
haha yep, ill do that now

2022-09-05 20:04 UTC, leon0399 commented
Perfect! If you have any further questions or just feeling to discuss anything feel free to contact me on Discord: leon0399#7352 or Telegram: @leon0399

2022-09-05 20:04 UTC, merged

2022-10-05 01:34 UTC, leon0399 commented
@sanjay900 how's your AliExpress shopping? Would love to see your approach to hardware! I will be really grateful if you can share your progress in discord and we can discuss which hardware work the best!

2022-10-05 01:38 UTC, sanjay900 commented
At the moment im waiting on some mates that are doing motor testing and they are waiting for motors to arrive, however my motor controllers and some little vibration motors have arrive, and so have all my esp32s. Im busy working on another project at the moment though so i haven't really been putting much into this currently

2022-10-12 08:01 UTC, leon0399 commented
> At the moment im waiting on some mates that are doing motor testing and they are waiting for motors to arrive

Sounds awesome! I'll be really happy, if you share results of your motor experiments! 🙏 Choosing right motor is really important for feedback quality! 🤞